line-length = 100

lint.select = ["ALL"]

lint.ignore = [
    "ANN",    # flake8-annotations
    "D100",   # undocumented-public-module
    "D101",   # undocumented-public-class
    "D102",   # undocumented-public-method
    "D103",   # undocumented-public-function
    "D104",   # undocumented-public-package
    "D105",   # undocumented-magic-method
    "D106",   # undocumented-public-nested-class
    "D107",   # undocumented-public-init
    "D211",   # blank-line-before-class
    "D213",   # multi-line-summary-second-line
    "PT009",  # pytest-unittest-assertion
]

exclude = ["*migrations*", ".git/", ".venv"]

target-version = "py312"

[lint.flake8-quotes]
inline-quotes = "single"

[format]
quote-style = "single"
