# Generated by Django 5.0 on 2024-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('regular', 'Regular User')], default='regular', max_length=20),
        ),
    ]
