# Generated by Django 5.0 on 2024-01-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0002_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosphere',
            options={'verbose_name': 'Фотосфера', 'verbose_name_plural': 'Фотосферы'},
        ),
    ]
