# Generated by Django 5.0 on 2024-01-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0003_alter_photosphere_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationpoints',
            options={'verbose_name': 'Точка информации', 'verbose_name_plural': 'Точки информации'},
        ),
        migrations.AlterModelOptions(
            name='teleportationpoint',
            options={'verbose_name': 'Точка перемещения', 'verbose_name_plural': 'Точки перемещения'},
        ),
    ]
