# Generated by Django 5.0 on 2024-01-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0004_alter_informationpoints_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teleportationpoint',
            options={},
        ),
        migrations.AlterField(
            model_name='informationpoints',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='informationpoints',
            name='photo_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guidein_space.photosphere', verbose_name='Фотосфера'),
        ),
        migrations.AlterField(
            model_name='informationpoints',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photosphere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photosphere',
            name='image_path',
            field=models.ImageField(upload_to='images/', verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='photosphere',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teleportationpoint',
            name='photo_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guidein_space.photosphere', verbose_name='Фотосфера'),
        ),
        migrations.AlterField(
            model_name='teleportationpoint',
            name='target_photo_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_teleportation_points', to='guidein_space.photosphere', verbose_name='Фотосфера для перемещения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('regular', 'Regular User')], default='regular', max_length=20, verbose_name='Роль'),
        ),
    ]
