# Generated by Django 5.0 on 2024-02-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0008_remove_photosphere_main_sphere_project_main_sphere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosphere',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_sphere',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('main_sphere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_main_sphere', to='guidein_space.photosphere', verbose_name='Основная фотосфера')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_spheres', to='guidein_space.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AddField(
            model_name='photosphere',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photo_spheres', to='guidein_space.location', verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='main_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_main_location', to='guidein_space.location', verbose_name='Основная локация'),
        ),
    ]
