# Generated by Django 5.0 on 2024-03-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0009_remove_photosphere_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(default='covers/default_cover.png', upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
