# Generated by Django 5.0 on 2024-03-21 20:21

import colorfield.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0010_project_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpoint',
            name='x',
        ),
        migrations.RemoveField(
            model_name='informationpoint',
            name='y',
        ),
        migrations.RemoveField(
            model_name='informationpoint',
            name='z',
        ),
        migrations.RemoveField(
            model_name='movepoint',
            name='x',
        ),
        migrations.RemoveField(
            model_name='movepoint',
            name='y',
        ),
        migrations.RemoveField(
            model_name='movepoint',
            name='z',
        ),
        migrations.AddField(
            model_name='informationpoint',
            name='pitch',
            field=models.FloatField(default=0, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationpoint',
            name='yaw',
            field=models.FloatField(default=0, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movepoint',
            name='pitch',
            field=models.FloatField(default=0, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movepoint',
            name='yaw',
            field=models.FloatField(default=0, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movepoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ImagePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('coordinates', models.JSONField(verbose_name='Координаты точек изображения')),
                ('photo_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_points', to='guidein_space.photosphere', verbose_name='Фотосфера')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='PolygonPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinates', models.JSONField(verbose_name='Координаты точек полигона')),
                ('fill', colorfield.fields.ColorField(default='rgba(255, 255, 255, 1)', image_field=None, max_length=25, samples=None, verbose_name='Цвет заливки')),
                ('stroke', colorfield.fields.ColorField(default='rgba(255, 255, 255, 1)', image_field=None, max_length=25, samples=None, verbose_name='Цвет границы')),
                ('stroke_width', models.CharField(max_length=20, verbose_name='Ширина границы')),
                ('photo_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_points', to='guidein_space.photosphere', verbose_name='Фотосфера')),
            ],
            options={
                'verbose_name': 'Полигон',
                'verbose_name_plural': 'Полигоны',
            },
        ),
        migrations.CreateModel(
            name='PolyLinePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinates', models.JSONField(verbose_name='Координаты точек линии')),
                ('stroke', colorfield.fields.ColorField(default='rgba(255, 255, 255, 1)', image_field=None, max_length=25, samples=None, verbose_name='Цвет линии')),
                ('stroke_width', models.CharField(max_length=20, verbose_name='Ширина линии')),
                ('stroke_linecap', models.CharField(max_length=20, verbose_name='Cтиль концов линии')),
                ('stroke_linejoin', models.CharField(max_length=20, verbose_name='Стиль соединения углов линии')),
                ('photo_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polyline_points', to='guidein_space.photosphere', verbose_name='Фотосфера')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
            },
        ),
        migrations.CreateModel(
            name='VideoPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('coordinates', models.JSONField(verbose_name='Координаты точек видео')),
                ('enable_chroma_key', models.BooleanField(default=False, verbose_name='Хромакей')),
                ('photo_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_points', to='guidein_space.photosphere', verbose_name='Фотосфера')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
