# Generated by Django 5.0 on 2024-03-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0011_remove_informationpoint_x_remove_informationpoint_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygonpoint',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='polygonpoint',
            name='opacity',
            field=models.CharField(default='1', max_length=20, verbose_name='Прозрачность полигона'),
        ),
        migrations.AddField(
            model_name='polygonpoint',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='polylinepoint',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='polylinepoint',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='videopoint',
            name='color_chroma_key',
            field=models.CharField(default='rgba(4, 244, 5, 1);', max_length=35, verbose_name='Цвет хромакея'),
        ),
        migrations.AlterField(
            model_name='informationpoint',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='informationpoint',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='polygonpoint',
            name='coordinates',
            field=models.JSONField(blank=True, default=[], verbose_name='Координаты точек полигона'),
        ),
        migrations.AlterField(
            model_name='polygonpoint',
            name='stroke_width',
            field=models.IntegerField(blank=True, default=1, verbose_name='Ширина границы'),
        ),
        migrations.AlterField(
            model_name='polylinepoint',
            name='coordinates',
            field=models.JSONField(blank=True, default=[], verbose_name='Координаты точек линии'),
        ),
        migrations.AlterField(
            model_name='polylinepoint',
            name='stroke_linecap',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cтиль концов линии'),
        ),
        migrations.AlterField(
            model_name='polylinepoint',
            name='stroke_linejoin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Стиль соединения углов линии'),
        ),
        migrations.AlterField(
            model_name='polylinepoint',
            name='stroke_width',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='Ширина линии'),
        ),
    ]
