# Generated by Django 5.0 on 2024-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidein_space', '0012_polygonpoint_description_polygonpoint_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonpoint',
            name='coordinates',
            field=models.JSONField(blank=True, default=list, verbose_name='Координаты точек полигона'),
        ),
        migrations.AlterField(
            model_name='polylinepoint',
            name='coordinates',
            field=models.JSONField(blank=True, default=list, verbose_name='Координаты точек линии'),
        ),
    ]
