# Generated by Django 5.0 on 2023-12-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0002_alter_photosphere_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleportationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('destination_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleportation_points', to='sphereapp.photosphere')),
            ],
        ),
    ]
