# Generated by Django 5.0 on 2023-12-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0004_remove_teleportationpoint_destination_sphere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleportationpoint',
            name='photo_sphere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sphereapp.photosphere'),
        ),
    ]
