# Generated by Django 5.0 on 2024-01-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0004_alter_informationpoints_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPositionViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('photo_sphere', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sphereapp.photosphere')),
            ],
            options={
                'verbose_name': 'Стартовая позиция',
                'verbose_name_plural': 'Стартовые позиции',
            },
        ),
    ]
