# Generated by Django 5.0 on 2024-02-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0006_project_photosphere_main_sphere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleportationpoint',
            name='photo_sphere',
        ),
        migrations.RemoveField(
            model_name='teleportationpoint',
            name='target_photo_sphere',
        ),
        migrations.RenameField(
            model_name='photosphere',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='photosphere',
            name='main_sphere',
            field=models.BooleanField(default=False, verbose_name='Основная фотосфера'),
        ),
        migrations.CreateModel(
            name='InformationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('photo_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_points', to='sphereapp.photosphere', verbose_name='Фотосфера')),
            ],
            options={
                'verbose_name': 'Точка информации',
                'verbose_name_plural': 'Точки информации',
            },
        ),
        migrations.CreateModel(
            name='MovePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('photo_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_points', to='sphereapp.photosphere', verbose_name='Фотосфера')),
                ('target_photo_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_move_points', to='sphereapp.photosphere', verbose_name='Целевая фотосфера')),
            ],
            options={
                'verbose_name': 'Точка перемещения',
                'verbose_name_plural': 'Точки перемещения',
            },
        ),
        migrations.DeleteModel(
            name='InformationPoints',
        ),
        migrations.DeleteModel(
            name='TeleportationPoint',
        ),
    ]
