# Generated by Django 5.0 on 2023-12-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0006_alter_teleportationpoint_photo_sphere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleportationpoint',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='teleportationpoint',
            name='photo_sphere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sphereapp.photosphere'),
        ),
        migrations.AlterField(
            model_name='teleportationpoint',
            name='target_photo_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_points', to='sphereapp.photosphere'),
        ),
    ]
