# Generated by Django 5.0 on 2024-02-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0007_remove_teleportationpoint_photo_sphere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosphere',
            name='main_sphere',
        ),
        migrations.AddField(
            model_name='project',
            name='main_sphere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_main_sphere', to='sphereapp.photosphere', verbose_name='Основная фотосфера'),
        ),
    ]
