# Generated by Django 5.0 on 2023-12-27 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0008_alter_teleportationpoint_photo_sphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleportationpoint',
            name='target_photo_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_teleportation_points', to='sphereapp.photosphere'),
        ),
    ]
