# Generated by Django 5.0 on 2023-12-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0009_alter_teleportationpoint_target_photo_sphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleportationpoint',
            name='photo_sphere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sphereapp.photosphere'),
        ),
    ]
