# Generated by Django 5.0 on 2023-12-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0011_alter_teleportationpoint_photo_sphere'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo_sphere', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='sphereapp.photosphere')),
            ],
        ),
    ]
