# Generated by Django 5.0 on 2024-01-11 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0012_informationpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpoints',
            name='photo_sphere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sphereapp.photosphere'),
        ),
        migrations.AlterField(
            model_name='teleportationpoint',
            name='photo_sphere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sphereapp.photosphere'),
        ),
    ]
