# Generated by Django 4.2.3 on 2023-12-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphereapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosphere',
            name='image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
